id: IAB61A1A2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:29:25+00:00'
last_modified: '2022-06-07T16:32:41.374972+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6188
  title: གནས་ཡིག་ཕྱོགས་བསྒྲིགས་རྫོགས་ལྡན་གསར་པའི་འོད་སྣང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B989:
      image_group_id: I1KG6221
      title: ''
      total_pages: 270
      order: 1
      base_file: B989.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
